<a href="https://colab.research.google.com/github/jeffheaton/app_deep_learning/blob/main/assignments/assignment_yourname_t81_558_class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# T81-558: Applications of Deep Neural Networks
* Instructor: [Jeff Heaton](https://sites.washu.edu/jeffheaton/), McKelvey School of Engineering, [Washington University in St. Louis](https://engineering.washu.edu/index.html)
* For more information visit the [class website](https://sites.washu.edu/jeffheaton/t81-558/).

**Module 2 Assignment: Creating Columns in Pandas**

**Student Name: Your Name**

# Assignment Instructions

For this assignment, you will use the **reg-36-data.csv** dataset.  This file contains a dataset that I generated specifically for this class.  You can find the CSV file on my data site, at this location: [reg-36-data.csv](http://data.heatonresearch.com/data/t81-558/datasets/reg-36-data.csv).

For this assignment, load and modify the data set.  You will submit this modified dataset to the **submit** function.  See [Assignment #1](https://github.com/jeffheaton/app_deep_learning/blob/main/assignments/assignment_yourname_t81_558_class1.ipynb) for details on how to submit an assignment or check that one was submitted.

Modify the dataset as follows:

* Add a column named *ratio* that is *max* divided by *number*.  Leave *max* and *number* in the dataframe.
* Replace the *cat2* column with dummy variables. e.g. 'cat2_CA-0', 'cat2_CA-1',
       'cat2_CA-10', 'cat2_CA-11', 'cat2_CA-12', ...
* Replace the *item* column with dummy variables, e.g. 'item_IT-0', 'item_IT-1',
       'item_IT-10', 'item_IT-11', 'item_IT-12', ...
* For field *length* replace missing values with the median of *length*.
* For field *height* replace missing with median and convert to zscore.
* Remove all other columns.
* Your submitted dataframe will have these columns: 'height', 'max', 'number', 'length', 'ratio', 'cat2_CA-0', 'cat2_CA-1',
       'cat2_CA-10', 'cat2_CA-11', 'cat2_CA-12', 'cat2_CA-13', 'cat2_CA-14',
       'cat2_CA-15', 'cat2_CA-16', 'cat2_CA-17', 'cat2_CA-18', 'cat2_CA-19',
       'cat2_CA-1A', 'cat2_CA-1B', 'cat2_CA-1C', 'cat2_CA-1D', 'cat2_CA-1E',
       'cat2_CA-1F', 'cat2_CA-2', 'cat2_CA-20', 'cat2_CA-21', 'cat2_CA-22',
       'cat2_CA-23', 'cat2_CA-24', 'cat2_CA-25', 'cat2_CA-26', 'cat2_CA-27',
       'cat2_CA-3', 'cat2_CA-4', 'cat2_CA-5', 'cat2_CA-6', 'cat2_CA-7',
       'cat2_CA-8', 'cat2_CA-9', 'cat2_CA-A', 'cat2_CA-B', 'cat2_CA-C',
       'cat2_CA-D', 'cat2_CA-E', 'cat2_CA-F', 'item_IT-0', 'item_IT-1',
       'item_IT-10', 'item_IT-11', 'item_IT-12', 'item_IT-13', 'item_IT-14',
       'item_IT-15', 'item_IT-16', 'item_IT-17', 'item_IT-18', 'item_IT-19',
       'item_IT-1A', 'item_IT-1B', 'item_IT-1C', 'item_IT-1D', 'item_IT-1E',
       'item_IT-2', 'item_IT-3', 'item_IT-4', 'item_IT-5', 'item_IT-6',
       'item_IT-7', 'item_IT-8', 'item_IT-9', 'item_IT-A', 'item_IT-B',
       'item_IT-C', 'item_IT-D', 'item_IT-E', 'item_IT-F'.

# Google CoLab Instructions

If you are using Google CoLab, it will be necessary to mount your GDrive so that you can send your notebook during the submit process.  Running the following code will map your GDrive to ```/content/drive```.

In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("T81_558_KEY")

# Assignment Submission Library

Run the following code to install the assignment submission package (`jh_submit`). All of the submission, listing, and file-checking utilities used in this notebook live in this package.

In [3]:
# Assignment submission package
!pip install https://s3.us-east-1.amazonaws.com/data.heatonresearch.com/library/jh_submit-0.1.0-py3-none-any.whl
import jh_submit

Collecting jh-submit==0.1.0
  Using cached jh_submit-0.1.0-py3-none-any.whl (17 kB)
Requirement already satisfied: pandas in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from jh-submit==0.1.0) (3.0.5)
Requirement already satisfied: pillow in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from jh-submit==0.1.0) (12.3.0)
Requirement already satisfied: requests in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from jh-submit==0.1.0) (2.34.2)
Requirement already satisfied: numpy>=1.26.0 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from pandas->jh-submit==0.1.0) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from pandas->jh-submit==0.1.0) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->jh-submit==0.1.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from requests->jh-submit==0.1.0) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from requests->jh-submit==0.1.0) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from requests->jh-submit==0.1.0) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/clever/miniconda3/envs/algo-course/lib/python3.12/site-packages (from requests->jh-submit==0.1.0) (2026.7.22)

# Assignment #2 Sample Code

The following code provides a starting point for this assignment.

In [14]:
import os
import pandas as pd
from scipy.stats import zscore

# You must identify your source file.  (modify for your local setup)
file="/home/clever/Projects/Python/ml_course/app_deep_learning/assignments/assignment_Maksim_t81_558_class2.ipynb" 
# Begin assignment
df = pd.read_csv("http://data.heatonresearch.com/data/t81-558/datasets/reg-36-data.csv")
print(len(df))

df.drop('id',axis=1,inplace=True)
df.drop('convention',axis=1,inplace=True)
display(df)

499

,height,max,cat2,number,usage,region,length,code,power,item,weight,country,target
0,4284.51,44907,CA-E,16669,US-7,RE-4,12471.1127,CO-B,27351.36,IT-17,13722,CO-1,44098.106769
1,806.88,48831,CA-A,8652,US-20,RE-15,10035.7085,CO-E,42323.89,IT-1E,33779,CO-0,95567.294044
2,2859.80,40760,CA-16,23103,US-17,RE-1D,14442.6566,CO-5,30660.91,IT-14,26633,CO-23,48583.507153
3,5823.87,33597,CA-9,17680,US-10,RE-1D,15121.4937,CO-B,59456.24,IT-8,14537,CO-11,130572.202064
4,NaN,29848,CA-9,24136,US-21,RE-4,18093.9147,CO-4,46998.44,IT-5,21135,CO-1E,85768.812850
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,41369,CA-22,21155,US-23,RE-1C,11691.7957,CO-C,53652.65,IT-C,24004,CO-10,123770.348457
495,2789.42,45004,CA-3,24213,US-1E,RE-1D,13873.7262,CO-8,65085.49,IT-5,54293,CO-18,152139.417494
496,NaN,65793,CA-27,15942,US-18,RE-A,14585.8900,CO-4,51806.63,IT-0,27490,CO-8,110193.578785
497,2623.75,68441,CA-C,20380,US-1A,RE-14,12625.3643,CO-C,27849.38,IT-18,18084,CO-11,45255.517785
498,NaN,45556,CA-19,21831,US-3,RE-F,9852.6036,CO-A,39085.13,IT-6,13774,CO-26,86076.947013

In [15]:
# Add a column named *ratio* that is *max* divided by *number*.  Leave *max* and *number* in the dataframe.

print(f"number has na? {pd.isnull(df['number']).values.any()}")
print(f"number has 0s {(df['number'].values == 0).any()}")
print(f"max has na? {pd.isnull(df['max']).values.any()}")
df["ratio"] = df["max"] /  df["number"]

number has na? False
number has 0s False
max has na? False

In [16]:
# Replace the *cat2* column with dummy variables. e.g. 'cat2_CA-0', 'cat2_CA-1',
#       'cat2_CA-10', 'cat2_CA-11', 'cat2_CA-12', ...
dummies = pd.get_dummies(df["cat2"], prefix="cat2")
df = pd.concat([df, dummies], axis=1)
df.drop(columns={"cat2"}, inplace=True)

In [17]:
# * Replace the *item* column with dummy variables, e.g. 'item_IT-0', 'item_IT-1',
#        'item_IT-10', 'item_IT-11', 'item_IT-12', ...
dummies = pd.get_dummies(df["item"], prefix="item")
df = pd.concat([df, dummies], axis=1)
df.drop(columns={"item"}, inplace=True)
display(df)

,height,max,number,usage,region,length,code,power,weight,country,...,item_IT-6,item_IT-7,item_IT-8,item_IT-9,item_IT-A,item_IT-B,item_IT-C,item_IT-D,item_IT-E,item_IT-F
0,4284.51,44907,16669,US-7,RE-4,12471.1127,CO-B,27351.36,13722,CO-1,...,False,False,False,False,False,False,False,False,False,False
1,806.88,48831,8652,US-20,RE-15,10035.7085,CO-E,42323.89,33779,CO-0,...,False,False,False,False,False,False,False,False,False,False
2,2859.80,40760,23103,US-17,RE-1D,14442.6566,CO-5,30660.91,26633,CO-23,...,False,False,False,False,False,False,False,False,False,False
3,5823.87,33597,17680,US-10,RE-1D,15121.4937,CO-B,59456.24,14537,CO-11,...,False,False,True,False,False,False,False,False,False,False
4,NaN,29848,24136,US-21,RE-4,18093.9147,CO-4,46998.44,21135,CO-1E,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,41369,21155,US-23,RE-1C,11691.7957,CO-C,53652.65,24004,CO-10,...,False,False,False,False,False,False,True,False,False,False
495,2789.42,45004,24213,US-1E,RE-1D,13873.7262,CO-8,65085.49,54293,CO-18,...,False,False,False,False,False,False,False,False,False,False
496,NaN,65793,15942,US-18,RE-A,14585.8900,CO-4,51806.63,27490,CO-8,...,False,False,False,False,False,False,False,False,False,False
497,2623.75,68441,20380,US-1A,RE-14,12625.3643,CO-C,27849.38,18084,CO-11,...,False,False,False,False,False,False,False,False,False,False
498,NaN,45556,21831,US-3,RE-F,9852.6036,CO-A,39085.13,13774,CO-26,...,True,False,False,False,False,False,False,False,False,False

In [18]:
from scipy.stats import zscore
# * For field *length* replace missing values with the median of *length*.
med = df["length"].median()
df["length"] = df["length"].fillna(med)
# * For field *height* replace missing with median and convert to zscore.
med = df["height"].median()
df["height"] = df["height"].fillna(med)
df["height"] = zscore(df["height"])
display(df)

,height,max,number,usage,region,length,code,power,weight,country,...,item_IT-6,item_IT-7,item_IT-8,item_IT-9,item_IT-A,item_IT-B,item_IT-C,item_IT-D,item_IT-E,item_IT-F
0,0.496557,44907,16669,US-7,RE-4,12471.1127,CO-B,27351.36,13722,CO-1,...,False,False,False,False,False,False,False,False,False,False
1,-1.419844,48831,8652,US-20,RE-15,10035.7085,CO-E,42323.89,33779,CO-0,...,False,False,False,False,False,False,False,False,False,False
2,-0.288551,40760,23103,US-17,RE-1D,14442.6566,CO-5,30660.91,26633,CO-23,...,False,False,False,False,False,False,False,False,False,False
3,1.344844,33597,17680,US-10,RE-1D,15121.4937,CO-B,59456.24,14537,CO-11,...,False,False,True,False,False,False,False,False,False,False
4,-0.000328,29848,24136,US-21,RE-4,18093.9147,CO-4,46998.44,21135,CO-1E,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,-0.000328,41369,21155,US-23,RE-1C,11691.7957,CO-C,53652.65,24004,CO-10,...,False,False,False,False,False,False,True,False,False,False
495,-0.327335,45004,24213,US-1E,RE-1D,13873.7262,CO-8,65085.49,54293,CO-18,...,False,False,False,False,False,False,False,False,False,False
496,-0.000328,65793,15942,US-18,RE-A,14585.8900,CO-4,51806.63,27490,CO-8,...,False,False,False,False,False,False,False,False,False,False
497,-0.418630,68441,20380,US-1A,RE-14,12625.3643,CO-C,27849.38,18084,CO-11,...,False,False,False,False,False,False,False,False,False,False
498,-0.000328,45556,21831,US-3,RE-F,9852.6036,CO-A,39085.13,13774,CO-26,...,True,False,False,False,False,False,False,False,False,False

In [19]:
keep_columns = [  'height', 'max', 'number', 'length', 'ratio', 'cat2_CA-0', 'cat2_CA-1','cat2_CA-10', 'cat2_CA-11', 'cat2_CA-12', 'cat2_CA-13', 'cat2_CA-14',
       'cat2_CA-15', 'cat2_CA-16', 'cat2_CA-17', 'cat2_CA-18', 'cat2_CA-19',
       'cat2_CA-1A', 'cat2_CA-1B', 'cat2_CA-1C', 'cat2_CA-1D', 'cat2_CA-1E',
       'cat2_CA-1F', 'cat2_CA-2', 'cat2_CA-20', 'cat2_CA-21', 'cat2_CA-22',
       'cat2_CA-23', 'cat2_CA-24', 'cat2_CA-25', 'cat2_CA-26', 'cat2_CA-27',
       'cat2_CA-3', 'cat2_CA-4', 'cat2_CA-5', 'cat2_CA-6', 'cat2_CA-7',
       'cat2_CA-8', 'cat2_CA-9', 'cat2_CA-A', 'cat2_CA-B', 'cat2_CA-C',
       'cat2_CA-D', 'cat2_CA-E', 'cat2_CA-F', 'item_IT-0', 'item_IT-1',
       'item_IT-10', 'item_IT-11', 'item_IT-12', 'item_IT-13', 'item_IT-14',
       'item_IT-15', 'item_IT-16', 'item_IT-17', 'item_IT-18', 'item_IT-19',
       'item_IT-1A', 'item_IT-1B', 'item_IT-1C', 'item_IT-1D', 'item_IT-1E',
       'item_IT-2', 'item_IT-3', 'item_IT-4', 'item_IT-5', 'item_IT-6',
       'item_IT-7', 'item_IT-8', 'item_IT-9', 'item_IT-A', 'item_IT-B',
       'item_IT-C', 'item_IT-D', 'item_IT-E', 'item_IT-F']
print(set(df.columns) - set(keep_columns))
df = df[df.columns.intersection(keep_columns)]
display(df)

{'weight', 'region', 'country', 'code', 'target', 'power', 'usage'}

,height,max,number,length,ratio,cat2_CA-0,cat2_CA-1,cat2_CA-10,cat2_CA-11,cat2_CA-12,...,item_IT-6,item_IT-7,item_IT-8,item_IT-9,item_IT-A,item_IT-B,item_IT-C,item_IT-D,item_IT-E,item_IT-F
0,0.496557,44907,16669,12471.1127,2.694043,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,-1.419844,48831,8652,10035.7085,5.643897,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,-0.288551,40760,23103,14442.6566,1.764273,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1.344844,33597,17680,15121.4937,1.900283,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,-0.000328,29848,24136,18093.9147,1.236659,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,-0.000328,41369,21155,11691.7957,1.955519,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
495,-0.327335,45004,24213,13873.7262,1.858671,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
496,-0.000328,65793,15942,14585.8900,4.127023,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
497,-0.418630,68441,20380,12625.3643,3.358243,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
498,-0.000328,45556,21831,9852.6036,2.086757,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [20]:

## Submit assignment
df.to_csv('2.csv',index=False)
jh_submit.client.submit(source_file=file,data=[df],key=api_key,course='t81-558',no=2)

Success: Submitted Assignment 2 (t81-558) for maksim:
You have submitted this assignment 2 times. (this is fine)

No errors, warnings, or notes on your data. Rock on! You will probably do well, but no guarantee. :-)